name: Build and Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
      - uses: actions/checkout@v2
      - name: Install and Build
        run: |
          pnpm install
          pnpm run build
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.7
        path: build
  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1